from array import *
print("Array Method")
print("1. append(): Appending values to array.")
print("2. insert(): Inserting values to given index.")
print("3. extend(): Extending array with more than one value.")
print("4. fromlist(): Adding items from list.")
print("5. remove(): Removing any elements from array.")
print("6. pop(): Remove last array element.")
print("7. index(): Fetching element through its index.")
print("8. reverse(): Reversing array.")
print("9. buffer_info(): Getting buffer info.")
print("10. count(): Count number of occurance of an element.")
print("11. tostring(): Convert array to string.")
print("12. tolist(): Convert array to list.")
print("13. fromstring(): Appending string to character array.")
print("14. test_duplicate(): Returns True if any element occurs at least twice.")
print()
print("Using for loop:")
arr1 = array("i", [1, 2, 4, 3])
print(arr1)
for i in arr1:
    print(i, end = " ")

print()
print()
print("Using extend method:")
arr2 = array("i", [1, 2])
print(arr2)
arr2.extend([3, 4])
print(arr2)

print()
print("Using insert method:")
arr3 = array("i", [2, 3])
print(arr3)
arr3.insert(0, 1)
print(arr3)

print()
print("Using append method: ")
arr4 = array("i", [1, 2, 3])
print(arr4)
arr4.append(3)
print(arr4)

print()
print("Usinf fromlist method: ")
arr5 = [5, 6, 7]
print(arr2)
arr4.fromlist(arr5)
print(arr4)

print()
print("Using remove method: ")
arr6 = array("i", [1, 2, 3, 4, 5, 6, 7, 8])
print(arr6)
arr6.remove(2)
print("After removing element: ", arr6)

print()
print("Using pop method: ")
arr7 = array("i", [1, 2, 3, 4, 5, 6])
print(arr7)
arr7.pop()
print("After pop: ", arr7)

print()
print("using reverse method: ")
arr8 = array("i", [1, 2, 3, 4, 5, 6, 7, 8])
print(arr8)
arr8.reverse()
print("Reverse array: ", arr8)

print()
print("Using count method: ")
arr9 = array("i", [1, 2, 3 ,2, 4 , 4, 4, 2, 1, 4])
print(arr9)
print("Count of 2: ", arr9.count(2))
